name: 'customer_analytics_poc'
version: '1.0'
config-version: 2

profile: 'analytics_profile'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  customer_analytics_poc:
    staging:
      +materialized: view
    marts:
      intermediate:
        +materialized: table
      final:
        +materialized: table
